### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by drewokane** [tinloaf/autocomplete-plus-python-jedi#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.9.4
**Thrown From**: [autocomplete-plus-python-jedi](https://github.com/tinloaf/autocomplete-plus-python-jedi) package, v0.2.6
### Stack Trace

Uncaught SyntaxError: Unexpected token 

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fdrew.okane%2Fdev%2Fclimatology-research%2Fprojects%2Fbob%2Fradar_ingest%2Fradar_ingest.py%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22appVersion%22%3A%220.192.0%22%2C%22shellLoadTime%22%3A327%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fdrew.okane%2Fdev%2Fclimatology-research%2Fprojects%2Fbob%2Fradar_ingest%22%5D%7D:1

SyntaxError: Unexpected token 
    at Object.parse (native)
    at JediProvider.processData (/Users/drew.okane/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-provider.coffee:107:19)
    at Interface.<anonymous> (/Users/drew.okane/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-provider.coffee:75:24)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:166:7)
    at Interface._onLine (readline.js:195:10)
    at Interface.<anonymous> (readline.js:325:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:324:11)
    at Socket.ondata (readline.js:71:10)
```
### Commands

```
  3x -4:39.5 core:move-right (atom-text-editor.editor)
  3x -4:34.1 core:move-down (atom-text-editor.editor)
  8x -4:32.9 core:move-left (atom-text-editor.editor)
     -4:28.8 core:save (atom-text-editor.editor)
  3x -3:25.2 editor:newline (atom-text-editor.editor)
     -2:44.0 autocomplete-plus:cancel (atom-text-editor.editor)
  5x -2:43.0 core:backspace (atom-text-editor.editor)
     -2:38.6 snippets:next-tab-stop (atom-text-editor.editor)
     -2:38.6 snippets:expand (atom-text-editor.editor)
     -2:38.6 editor:indent (atom-text-editor.editor)
     -2:38.0 core:backspace (atom-text-editor.editor)
     -2:35.1 core:save (atom-text-editor.editor)
     -2:16.3 pane:show-next-item (atom-text-editor.editor)
     -2:08.9 pane:show-previous-item (atom-text-editor.editor)
     -1:46.9 core:save (atom-text-editor.editor)
     -1:17.6 core:move-right (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "texlicious",
      "autocomplete-plus-jedi",
      "autocomplete-jedi"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.10.0
autocomplete-plus-python-jedi, v0.2.6
language-latex, v0.6.1
language-matlab, v0.1.0
latex, v0.21.0
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by tinloaf** [comment]
This is very likely to be the same bug as #6 .. Are you able to reproduce this, i.e. does this happen in the same file all the time or the like?

**Comment by drewokane** [comment]
Unfortunately I can't reproduce this. So far this has happened only once.

**Comment by JohnPHogan** [comment]
![screen shot 2015-06-17 at 4 40 24 pm](https://cloud.githubusercontent.com/assets/7018415/8219420/9ea1f906-150f-11e5-830e-76d422e4f3d8.png)
I've been able to encounter this error as well:

SyntaxError: Unexpected token 
    at Object.parse (native)
    at JediProvider.processData (/Users/jph/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-provider.coffee:201:19)
    at Interface.<anonymous> (/Users/jph/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-provider.coffee:120:24)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:166:7)
    at Interface._onLine (readline.js:195:10)
    at Interface.<anonymous> (readline.js:325:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:324:11)
    at Socket.ondata (readline.js:71:10)

**Comment by NamanJn** [comment]
Me too.
![screen shot 2015-06-20 at 09 29 42](https://cloud.githubusercontent.com/assets/10748922/8266599/f24d89b4-172e-11e5-8642-fbeb790d4b99.png)

**Comment by tinloaf** [comment]
Hi! I'm sorry to reply so late, but I had hoped that this problem would vanish on it's own: This plugin has long been abandoned in favor of https://github.com/sadovnychyi/autocomplete-python ..

The Atom folks wanted to somehow mark my plugin as deprecated, but have not done so yet, as it seems. So, please switch over to that other one!
