### ISSUE TITLE
Feature request - play nicely with jhutchins/virtualenv

### ISSUE THREAD

**Issue by posita** [tinloaf/autocomplete-plus-python-jedi#12]
It appears that `autocomplete-plus-python-jedi` runs `jedi-cmd.py` at the time a new window is created and it persists (with whatever environment it got at that point) until that window is closed, whereas the [`virtualenv` Atom package](/jhutchins/virtualenv) allows for later context switching at the window level. This context switch is completely missed by `autocomplete-plus-python-jedi`.

It would be nice if there was some mechanism by which `autocomplete-plus-python-jedi` could restart the `jedi-cmd.py` under the new environment when it detects one. This may require coordination between the two projects. I have filed a sister issue (jhutchins/virtualenv#29) to track this.

**Comment by tinloaf** [comment]
Oh, now I see what you meant by that earlier. :) Yep, currently there is only one jedi-cmd process running. I was planning on having multiple of those running, in case you have multiple 'projects' open. Working in tandem with that package (that I did not know, thanks!) seems like a good idea.

**Comment by posita** [comment]
Migrated from https://github.com/tinloaf/autocomplete-plus-python-jedi/issues/7#issuecomment-95366119 for convenience:

## 

[I]f the [`virtualenv` Atom package](https://github.com/jhutchins/virtualenv) is installed, it seems to be ignored [by `autocomplete-plus-python-jedi`]. For example:

``` sh
% export WORKON_HOME="${HOME}/venvs"
% mkdir -p "${WORKON_HOME}"
% mkvirtualenv testjedi && "${HOME}/venvs/testjedi/bin/pip" install jedi
...
% .../Applications/Atom.app/Contents/Resources/app/atom.sh &
```

Now select `testjedi` from the `Packages` -> `Virtualenv` submenu. Open a `.py` file (or create a new one). Start typing. You'll get a ... jedi-not-found error (assuming jedi is not also installed along with the default python installation).

...

**Comment by posita** [comment]
> I was planning on having multiple of those running, in case you have multiple 'projects' open.

The good news is that it's probably acceptable to ~~assume~~ _impose a limit of_ one-project-per-window (at least until someone complains :wink:). Changes from the [`virtualenv` Atom package](https://github.com/jhutchins/virtualenv) seem to apply at the window level (rather than at the project level). The fact that each window has its own `PID` (at least on OS X and Linux, I have not verified on Windows) may make window granularity convenient?

**Comment by posita** [comment]
After thinking about this for half-a-minute, this kind of thing seems (potentially) bigger than just these two packages. Triggering a change in environment can happen in Java (i.e., with `JAVA_HOME`, etc.), Ruby (I can't remember the details, but I seem to remember it has its own proprietary analogy to Python's `virtualenv`), and probably many others. I can imagine a publish-subscribe model where packages that allow changing environments can publish messages like:

| Environment | Scope | Trigger |
| --- | --- | --- |
| `Java` | `/[Window ID]/[Project ID]` | `Restart` |
| `Python` | `/[Window ID]` | ... |
| `Ruby` | `/` (meaning the application level) | ... |

Other packages which depend on those environments (like `autocomplete-plus-python-jedi`) could subscribe to those messages and act accordingly when they receive them.

I don't know what other trigger there might be other than `Restart` (maybe `Reload("XYZ")` where `XYZ` was a module name, if that was appropriate to the environment), but those decisions could be left up to the developers writing packages in those environments? In theory, one could go all the way down to `/[Window ID]/[Project ID]/[File ID]`, although I'm not sure how practical that is?

**Comment by posita** [comment]
See also:
- http://blog.atom.io/2014/09/16/new-event-subscription-api.html
- https://github.com/atom/event-kit
- https://github.com/atom/emissary
- https://atom.io/docs/api/latest/Emitter
- https://atom.io/docs/api/latest/Task (not sure if this is relevant)

**Comment by posita** [comment]
See also @mattdeboard's https://github.com/jhutchins/virtualenv/issues/29#issuecomment-95797518.

**Comment by tinloaf** [comment]
Yeah, the event approach "feels right". If the events don't propagate between packages (did not check yet...), I think one could aks the Atom maintainers nicely...

**Comment by mattdeboard** [comment]
Actually, I think the rightest approach here would be if the virtualenv plugin offered a [service](http://blog.atom.io/2015/03/25/new-services-API.html) to notify of changes to virtualenv.

**Comment by posita** [comment]
It looks like [jhutchins/virtualenv](/jhutchins/virtualenv) is no longer being maintained. See also #29.

**Comment by tinloaf** [comment]
Hi! I'm sorry to reply so late, but I had hoped that this problem would vanish on it's own: This plugin has long been abandoned in favor of https://github.com/sadovnychyi/autocomplete-python ..

The Atom folks wanted to somehow mark my plugin as deprecated, but have not done so yet, as it seems. So, please switch over to that other one!
