### ISSUE TITLE
Jedi not found

### ISSUE THREAD

**Issue by sh4nks** [tinloaf/autocomplete-plus-python-jedi#24]
I am always getting this error message. I have installed jedi with pip afterwards but this error message still pops up.

> We could not find the jedi package in your python environment. Please make sure that you activated any virtual environment that you wanted to work in. Also make sure that you installed jedi. You can do so via a simple 'pip install jedi' command.

**Comment by Arcanemagus** [comment]
Looks like this may be a duplicate of https://github.com/tinloaf/autocomplete-plus-python-jedi/issues/17

**Comment by sh4nks** [comment]
Oh didn't see this issue. Yeah looks like the same one.
