### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by sanori** [tinloaf/autocomplete-plus-python-jedi#25]
### Steps to reproduce
1. I just installed autocomplete-plus-python-jedi
2. Entering "parser.p" while editing python code.
   (I have expected to autocomplete "print_help()" of optparse package.)
   The part of code is as follows:

```
import optparse
def main():
    usage = "Usage: %prog key_columns value_columns [files]"
    parser = optparse.OptionParser(usage=usage)
    (option, args) = parser.parse_args()
    if len(args) < 2:
        parser.p
```
1. Then 2 errors are occurred. 
   One is "write EPIPE" at events.js:141, and the other is "This socket is closed" at events.js:141.

This error is also occurred after restarting the atom editor.

**Atom Version**: 0.200.0
**System**: Windows 7
**Thrown From**: [autocomplete-plus-python-jedi](https://github.com/tinloaf/autocomplete-plus-python-jedi) package, v0.3.5
### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
    at exports._errnoException (util.js:734:11)
    at Socket._writeGeneric (net.js:668:26)
    at Socket._write (net.js:687:8)
    at doWrite (_stream_writable.js:295:12)
    at writeOrBuffer (_stream_writable.js:282:5)
    at Socket.Writable.write (_stream_writable.js:210:11)
    at Socket.write (net.js:612:40)
    at JediProvider.sendPathToJedi (C:\Users\jwjung\.atom\packages\autocomplete-plus-python-jedi\lib\jedi-provider.coffee:96:25)
    at JediProvider.createJediFor (C:\Users\jwjung\.atom\packages\autocomplete-plus-python-jedi\lib\jedi-provider.coffee:135:14)
    at JediProvider.getJediFor (C:\Users\jwjung\.atom\packages\autocomplete-plus-python-jedi\lib\jedi-provider.coffee:148:19)
```
### Commands

```
  3x -0:10.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:09.5.0 snippets:expand (atom-text-editor.editor.is-focused)
  5x -0:09.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus-python-jedi, v0.3.5

# Dev
No dev packages
```

**Comment by sanori** [comment]
After re-install the (Anaconda) python instead of original python(.org), it works.
It seems that the path to python.exe was not added to PATH variable.

If someone want to change this unkind message to "python executable was not found",
which module he or she fix? jedi? or autocomplete-plus-python-jedi?

It seems that there is some error handling near the line 75 of jedi-provider.coffee,
did this code not work?

**Comment by tinloaf** [comment]
Hi! I'm sorry to reply so late, but I had hoped that this problem would vanish on it's own: This plugin has long been abandoned in favor of https://github.com/sadovnychyi/autocomplete-python ..

The Atom folks wanted to somehow mark my plugin as deprecated, but have not done so yet, as it seems. So, please switch over to that other one!
