### ISSUE TITLE
virtualenv support

### ISSUE THREAD

**Issue by ergo** [tinloaf/autocomplete-plus-python-jedi#29]
Now that virtualenv package for atom doesn't work or load at all (in fact it looks like its been abandoned?), is there any solution one can use to point to project's virtualenv?

For example I store my envs in ~/venvs/*\* it would be great if I could for example create a file that would provide a path for the environment I want to use.

**Comment by posita** [comment]
If I can piggyback onto this request, it would be convenient to allow the plugin to infer which `virtualenv` to use based on the project dir. That way one could have two different project windows open in Atom which use two different `virtualenv`s.

I don't know the "right" way to go about this though. Check for the presence of `[PROJECT_DIR]/.venv/bin/python`? Read the `virtualenv` or `python` binary path from `[PROJECT_DIR]/.virtualenv` (probably better for Windoze users)? Both (degrade from one to the other)? Allow those paths to be set by the user?

**Comment by posita** [comment]
See also #9 (which is a slightly different issue, since it requests the ability to set the Python interpreter globally, I believe) as well as [saravanan-k90/python-jedi](/saravanan-k90/python-jedi).

**Comment by tinloaf** [comment]
Hi! I'm sorry to reply so late, but I had hoped that this problem would vanish on it's own: This plugin has long been abandoned in favor of https://github.com/sadovnychyi/autocomplete-python ..

The Atom folks wanted to somehow mark my plugin as deprecated, but have not done so yet, as it seems. So, please switch over to that other one!
