### ISSUE TITLE
cant uninstall, broke my usual autocomplete

### ISSUE THREAD

**Issue by codyc4321** [tinloaf/autocomplete-plus-python-jedi#31]
Why can I not uninstall this package? I clicked uninstall constantly, then tested by installing and quickly uninstalling other packages. Also, after installing this package, my autocompletion in general has broken and doesn't work

**Comment by codyc4321** [comment]
I also cannot enable it either, from the box it gives you in Atom, with the readme below it
![atomproblem](https://cloud.githubusercontent.com/assets/6758271/8674598/f0386748-2a0c-11e5-82dc-26472088f60d.png)

**Comment by codyc4321** [comment]
I have closed and restarted Atom, but not my PC yet I'm still working. After restarting atom same issue

**Comment by tinloaf** [comment]
Huh, that is very weird. This seems to rather be a bug with Atom itself, since the plugin has nothing to do with the install / deinstall process...

**Comment by codyc4321** [comment]
true
