### ISSUE TITLE
Jedi not found

### ISSUE THREAD

**Issue by exiva** [tinloaf/autocomplete-plus-python-jedi#7]
Installed the package with apm, and when I start a new editor and type I get

'We could not find the jedi package in your python environment. Please make sure that you activated any virtual environment that you wanted to work in. Also make sure that you installed jedi. You can do so via a simple 'pip install jedi' command.'

Installed jedi with `pip install jedi` as instructed, and get the same thing.

**Comment by tinloaf** [comment]
How do you start Atom? From a command line? If so, immediately prior to staring atom, please just start a python shell and type 'from jedi import api'. Does that work?

**Comment by dpwrussell** [comment]
I also have the issue that jedi was not bundled. The only python file bundled seems to be `~/.atom/packages/autocomplete-plus-python-jedi//lib/jedi-cmd.py`

`pip install jedi` did work for me though.

**Comment by exiva** [comment]
Doing pip install jedi, and then launching atom from the command line works. But launching from finder or alfred will get the jedi not found error.

Looking more into it, it appears the jedi submodule isn't pulled down when using apm from the command line. Grabbing jedi from their git repo and placing it manually works.

**Comment by dpwrussell** [comment]
As you would expect, using the Package MAanger from within Atom yields the same result as using apm on command line.

**Comment by tinloaf** [comment]
Oh, that's interesting. I'll have a look why APM did not really include the bundled Jedi into the package.

**Comment by posita** [comment]
_UPDATE: Filed as a separate issue. See #12._

## 

Also, if the [`virtualenv` Atom package](https://github.com/jhutchins/virtualenv) is installed, it seems to be ignored. For example:

``` sh
% export WORKON_HOME="${HOME}/venvs"
% mkdir -p "${WORKON_HOME}"
% mkvirtualenv testjedi && "${HOME}/venvs/testjedi/bin/pip" install jedi
...
% .../Applications/Atom.app/Contents/Resources/app/atom.sh &
```

Now select `testjedi` from the `Packages` -> `Virtualenv` submenu. Open a `.py` file (or create a new one). Start typing. You'll get a similar jedi-not-found error (assuming jedi is not also installed along with the default python installation).

I can file this as a separate issue if desired.

**Comment by tinloaf** [comment]
@posita As far as I can see, you did not activate the virtualenv? You used the virtualenv's pip to install jedi, so it's now installed in that environment, but your environment variables don't point to the virtualenv. If you do a "source "${HOME}/venvs/testjedi/bin/activate" directly before invoking atom, that should fix it?

**Comment by tinloaf** [comment]
By the way, I think were I know where the problem lies: Github does not include "git submodules" in releases. I'll have to copy jedi to my repository, will do so in the next release.

**Comment by posita** [comment]
_UPDATE: Filed as a separate issue. See #12._

## 

> @posita As far as I can see, you did not activate the virtualenv? You used the virtualenv's pip to install jedi, so it's now installed in that environment, but your environment variables don't point to the virtualenv. If you do a "source "${HOME}/venvs/testjedi/bin/activate" directly before invoking atom, that should fix it?

Setting up a python environment and starting Atom from within it (i.e., from the command line after calling `activate` or equivalent as you suggest) appears to work (see this https://github.com/tinloaf/autocomplete-plus-python-jedi/issues/6#issuecomment-95606672).

My observations may be a separate issue (and possibly belong to the [`virtualenv` Atom package](https://github.com/jhutchins/virtualenv)). If I understand correctly, that package is _supposed_ to perform the equivalent activation steps from _within_ Atom (i.e., such that it doesn't matter what the environment is at the time Atom is started).

**Comment by tinloaf** [comment]
This should be fixed in 0.2.7. Thanks for reporting!

**Comment by Anteru** [comment]
Doesn't work for me with 0.3.5, on Atom 0.199 and Linux. Interestingly, even starting atom from within a virtual environment which has a working jedi does not work. This is using Python3 on Ubuntu 15.04, if that is important.

The fix is to change line 16 in jedi-cmd.py to read `sys.path.append(my_path + '/external/jedi')`

**Comment by manudevelopia** [comment]
Thanks Anteru, your fix worked for me under Yosemite.

**Comment by tinloaf** [comment]
Ouch.. yes, it looks like my directory structure got somehow messed up. I'll clean this up later today. Thanks for that hint!
