### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by dpwrussell** [tinloaf/autocomplete-plus-python-jedi#9]
Would it be possible to have settings to contorl PYTHONPATH and the interpreter used? In the SublimeJedi plugin you can add custom `python_package_paths` to the global configuration. More importantly, SublimeJedi (because Project support is built-in to Sublime) has support for project specific settings. For example:

```
    "settings":
    {
        "python_interpreter_path": "~/.virtualenvs/omero/bin/python",
        "python_package_paths":
        [
            "~/.virtualenvs/omero/lib/python2.7/site-packages"
        ]
    }
```

As there isn't a built-in package manager for Atom (as yet), I'm unsure how this would work, but support for something like `python_package_paths` and `python_interpreter_path` at the global level would be great. I believe one could then use something like https://github.com/nirix/atom-editor-settings to make use of those settings on a per-project basis.

**Comment by mattdeboard** [comment]
This is also how emacs handles its jedi package.

**Comment by sadovnychyi** [comment]
I've added it here: https://github.com/sadovnychyi/autocomplete-plus-python-jedi/commit/b5a7590818dbe146d361a0afb03385cbe71e0a55
Awaiting for merge #15

**Comment by posita** [comment]
See also [saravanan-k90/python-jedi](/saravanan-k90/python-jedi).

**Comment by tinloaf** [comment]
Hi! I'm sorry to reply so late, but I had hoped that this problem would vanish on it's own: This plugin has long been abandoned in favor of https://github.com/sadovnychyi/autocomplete-python ..

The Atom folks wanted to somehow mark my plugin as deprecated, but have not done so yet, as it seems. So, please switch over to that other one!
